// import "./src/1-observable";
// import "./src/2-from-of";
// import "./src/3-interval";
// import "./src/4-range";
// import "./src/6-map-filter";
// import "./src/7-pluck";
// import "./src/8-tap"
// import "./src/9-first-last-startWith"
// import "./src/10-skip";
// import "./src/11-take";
// import "./src/12-throttle";
// import "./src/13-debounce";
// import "./src/14-scan-reduce";
// import "./src/15-concat";
// import "./src/16-merge";
// import "./src/17-combine-latest";
// import "./src/18-switch-map";
// import "./src/19-exhaust-map";
// import "./src/20-concatAll";
// import "./src/21-fromFetch";
// import "./src/22-observable-types";
// import "./src/23-behavior-subject";
import "./src/24-replay-subject";
